# Generated by Django 5.0.1 on 2024-02-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Опрос: ')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Заархивирован: ')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг: ')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(verbose_name='ID пользователя: ')),
                ('question_pk', models.IntegerField(verbose_name='ID вопроса: ')),
                ('answer_pk', models.IntegerField(verbose_name='ID ответа: ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос: ')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Заархивирован: ')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг: ')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests_app.survey', verbose_name='Опрос: ')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Заархивирован: ')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ: ')),
                ('following_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_answers', to='tests_app.question', verbose_name='Вопрос, следующий за этим ответом: ')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='tests_app.question', verbose_name='Вопрос: ')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='tests_app.survey', verbose_name='Опрос: ')),
            ],
        ),
    ]
